
models:
 - type: main
   engine: watsonxllm
   model: llama-2-70b-chat
   parameters:
      model_id: meta-llama/llama-2-70b-chat
      project_id: 8a7000bb-06e2-47c0-9e9a-4089443e4c5f
      params:
        MAX_NEW_TOKENS: 200
        DECODING_METHOD: "sample"
        TEMPERATURE: 1.5
        TOP_K: 50
        TOP_P: 1

instructions:
  - type: general
    content: |
      Below is a conversation between a user and a bot called the ABC Bot.
      The bot is designed to answer employee questions about the ABC Company.
      The bot is knowledgeable about the employee handbook and company policies.
      If the bot does not know the answer to a question, it truthfully says it does not know.


sample_conversation: |
  user "Hi there. Can you help me with some questions I have about the company?"
    express greeting and ask for assistance
  bot express greeting and confirm and offer assistance
    "Hi there! I'm here to help answer any questions you may have about the ABC Company. What would you like to know?"
  user "What's the company policy on paid time off?"
    ask question about benefits
  bot respond to question about benefits
    "The ABC Company provides eligible employees with up to two weeks of paid vacation time per year, as well as five paid sick days per year. Please refer to the employee handbook for more information."
    
rails:  
  output:
    flows:
      - self check output
      - check blocked terms
      - self check facts
      - check hallucination
  input:
    flows:
      - self check input
